class Config:
    SQL_SERVER = 'JOSEDELACRUZ25'
    DATABASE = 'Tienda2'
    DRIVER = 'SQL Server'
    CONNECTION_STRING = f'DRIVER={DRIVER};SERVER={SQL_SERVER};DATABASE={DATABASE};Trusted_Connection=yes;'